### ISSUE TITLE
The image won't build

### ISSUE THREAD

**Issue by mascip** [paimpozhil/DockerX2go#1]
Hi, I'm on debian 7.4 (amd64), here is what I get when I run 

```
/home/user/$ CID=$(docker run -p 2222:22 -t -d dock2go)  

Selecting previously unselected package bsdmainutils.
Preparing to unpack .../bsdmainutils_9.0.5ubuntu1_amd64.deb ...
Unpacking bsdmainutils (9.0.5ubuntu1) ...
Selecting previously unselected package man-db.
Preparing to unpack .../man-db_2.6.7.1-1_amd64.deb ...
Unpacking man-db (2.6.7.1-1) ...
Selecting previously unselected package fuse.
Preparing to unpack .../fuse_2.9.2-4ubuntu4_amd64.deb ...
Unpacking fuse (2.9.2-4ubuntu4) ...
Processing triggers for mime-support (3.54ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up libfuse2:amd64 (2.9.2-4ubuntu4) ...
Setting up fuse (2.9.2-4ubuntu4) ...
Creating fuse group...
Adding group `fuse' (GID 105) ...
Done.
Creating fuse device...
mknod: 'fuse-': Operation not permitted
makedev fuse c 10 229 root root 0660: failed
chown: cannot access '/dev/fuse': No such file or directory
dpkg: error processing package fuse (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.19-0ubuntu6) ...
Errors were encountered while processing:
 fuse
E: Sub-process /usr/bin/dpkg returned an error code (1)
2014/06/02 13:53:42 build: The command [/bin/sh -c apt-get install -y openssh-server xubuntu-desktop] returned a non-zero code: 100
```

**Comment by paimpozhil** [comment]
Looks like debian 7.4 does not allow fuse devices creation like the newer ubuntu system expects.

http://jtrancas.wordpress.com/2011/02/09/fuse-filesystems-lxc-container/

this may slightly help.

What is your docker version? can you update to the latest if you can.

**Comment by mascip** [comment]
Thank you :)

```
$ docker --version
Docker version 0.8.0, build cc3a8c8  
```

I was thinking of uninstalling Debian and going for the Latest Lubuntu instead. Now might be the time ;-)

One more question (unrelated to this particular issue) : how do you deal with data persistence for Firefox? (see my docker-desktop issue <a href="https://github.com/rogaha/docker-desktop/issues/20">here</a>)

**Comment by paimpozhil** [comment]
How do i deal with data persistence for Firefox? ( I DONT lol )

now to answer your issue:

I think with the -v ( volume from host ) you are doing it correctly to mount the firefox-data to the host.

Note -v volumes can be mounted read-writable, and by default they must be rw.

from the Docker docs : http://docs.docker.io/reference/commandline/cli/
--volumes-from argument. The container ID may be optionally suffixed with :ro or :rw to mount the volumes in read-only or read-write mode, respectively. By default, the volumes are mounted in the same mode (read write or read only) as the reference container.

You can try : -v /home/mascip/docker-desktop/firefox-data/$container_name:/home/docker/.mozilla/firefox/:rw

Also note you can setup a DATA only container to hold this data as well..
http://docs.docker.io/use/working_with_volumes/

**Comment by mascip** [comment]
:rw doesn't work with -v, but only with --volumes-from. I've seen that I could try a data-only container, but they say it dies when no container uses it, so I would regularly lost my data. Well, maybe I should try to check if that's true. Or I could ask on the mailing list.

Another solution would be to manually backup my data, like they explain in the last section of your last link: 

```
sudo docker run -rm --volumes-from DATA -v $(pwd):/backup busybox tar cvf /backup/backup.tar /data
```

It's annoying because I don't want to have to think about that, but it's better than nothing ;-)

**Comment by paimpozhil** [comment]
Data-only container does not die when no container uses it.

Its not true.

Data is lost ONLY if data only container is deleted and No other running
containers are using the volumes at the same time.

You just have to use the Data container.. and I have an idea to KEEP the
data container running so you do not delete even by accident.

https://github.com/paimpozhil/WhatPanel/tree/master/data follow this!

On Mon, Jun 2, 2014 at 7:35 PM, Pierre Masci notifications@github.com
wrote:

> :rw doesn't work with -v, but only with --volumes-from. I've seen that I
> could try a data-only container, but they say it dies when no container
> uses it, so I would regularly lost my data. Well, maybe I should try, to
> check if that's true. Or I could ask on the mailing list.
> 
> Another solution would be to manually backup my data, like they explain in
> the last section of your last link: sudo docker run -rm --volumes-from DATA
> -v $(pwd):/backup busybox tar cvf /backup/backup.tar /data
> It's annoying because I don't want to have to think about that, but it's
> better than nothing ;-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/paimpozhil/DockerX2go/issues/1#issuecomment-44840610.

## 

Paim Pozhil

**Comment by mascip** [comment]
Thank you for your help paimpozhil. I don't manage to make the data folder writable. :rw doesn't seem to work. I think I will re-install my computer with Lubuntu. Maybe I will get better luck.

**Comment by mascip** [comment]
Weird... docker inspect says the volume is writeable, but firefox says it doesn't have the permission, and so does the ls command. I'm always a bit confused about these permission stuff... will investigate further.

**Comment by mascip** [comment]
It works!! Amazing! In the end I only had to do

```
sudo chmod 777 .mozilla/firefox
```

I also had to declare absolute paths for the volumes in the dockerfile, and use /home/docker/ instead of ~.

I even restarted my computer, and the data is still there. It seems perfect so far :-)
Thank a lot for your help.

**Comment by paimpozhil** [comment]
wow that is so great.. :)

On Mon, Jun 2, 2014 at 11:10 PM, Pierre Masci notifications@github.com
wrote:

> It works!! Amazing! In the end I only had to do
> 
> sudo chmod 777 .mozilla/firefox
> 
> I even restarted my computer, and the data is still there. It seems
> perfect so far :-)
> Thank a lot for your help.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/paimpozhil/DockerX2go/issues/1#issuecomment-44868010.

## 

Paim Pozhil

**Comment by paimpozhil** [comment]
Take a look at my centos image https://github.com/paimpozhil/DockerX2go/tree/master/centos 
when you can.

**Comment by mascip** [comment]
Why this one in particular? It looks a lot like the others.

-- Pierre Masci

**Comment by paimpozhil** [comment]
It seemed to me running better than ubuntus .. Near desktop experience

**Comment by mascip** [comment]
Nice cheers =) I hope to have the time to try it this week.

I don't know if you saw my other issue in docker-desktop:
https://github.com/rogaha/docker-desktop/issues/19
I use simple X11 forwarding with ssh ( to open firefox in a container I do:
ssh docker@172.17.42.1 firefox ), because xpra didn't work in my Debian (I
just installed Lubuntu instead, today). What is the advantage of using xpra
or x2go in addition to that?

-- Pierre Masci

**Comment by paimpozhil** [comment]
I answered there as well.

X2go gives you support for different Compression ( good for wan /internet based desktops ) , Sound  , file sharing ,etc out of the box.

When you are sitting next to the machine.. you can simply VNC/SSH doesnt matter much
