### ISSUE TITLE
Google Chrome/Chromium fail to start

### ISSUE THREAD

**Issue by gurjeet** [paimpozhil/DockerX2go#2]
Let me start by saying "Awesome Work!!".

I used the lxde/Dockerfile for creating a new container. Firefox worked flawlessly, and I was able to play some Youtube videos, with sound etc.

(Even though I wouldn't like the Chromium and Google Chrome to be installed by default) I couldn't start the Chrome and Chromium browsers. I clicked on both of them a few times in the hopes of some kind of window would show up, but no joy.

Looking at the output of `ps faux`, it seems the *-sandbox processes are created and alive, but marked as '<defunct>'. Something seems to be prohibiting these browsers from functioning correctly.

**Comment by paimpozhil** [comment]
Did you try /chrome.sh in terminal to start

**Comment by gurjeet** [comment]
When logged in as root in X2Go, I launched LXTerminal (from Accessories menu), and launched /chrome.sh. Here's the error message I get:

```
root@97ba06459b7e:~# /chrome.sh
[476:476:0615/192852:ERROR:simple_message_box_views.cc(208)] Unable to show a dialog outside the UI thread message loop: Google Chrome can not be run as root. - Please start Google Chrome as a normal user. To run as root, you must specify an alternate --user-data-dir for storage of profile information.
[0615/192852:ERROR:nacl_helper_linux.cc(236)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
root@97ba06459b7e:~#
```

I hadn't tried logging in as dockerx (non-root) user before, so I wanted to try the script as that user. But when I try to login as dockerx from X2GO client, I get a dialog box with the error message:

```
Connection failed DBI connect('dbname=/var/lib/x2go/x2go_sessions','',...) failed: unable to open database file at /usr/lib/x2go/x2gosqlitewrapper.pl line 89. [limit users] at /usr/lib/x2go/x2gosqlitewrapper.pl line 89.
```

More info:
Host OS: Ubuntu 12.04
Host Kernel: 3.11.0-19-generic #33~precise1-Ubuntu SMP Wed Mar 12 21:16:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Docker version: 1.0.0, build 63fe64c

I hope those messages are helpful for you to diagnose this further.

**Comment by paimpozhil** [comment]
This happens because the dockerx user is not in the group "x2gousers"

I have added a fix to /run.sh see if it now allows you to login to dockerx and hence launch the chrome

I tested this on a Ubuntu 14.04 host with docker 1.0 and it works :+1:

**Comment by zerlgi** [comment]
It would probably be possible to run chrome with `--no-sandbox` added
or with `--no-sandbox  --disable-setuid-sandbox`

**Comment by paimpozhil** [comment]
My /chrome.sh basically does that

On Thu, Jun 19, 2014 at 8:58 PM, zerlgi notifications@github.com wrote:

> It would probably be possible to run chrome with --no-sandbox added
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/paimpozhil/DockerX2go/issues/2#issuecomment-46575488.

## 

Paim Pozhil
