### ISSUE TITLE
Every X2Go session leaves ssh-agent behind

### ISSUE THREAD

**Issue by gurjeet** [paimpozhil/DockerX2go#3]
I am using the lxde/Dockerfile to create a container, and I noticed that every time I login and logout from X2Go client, a new ssh-agent process is left behind.

How to test:
1. Keep one console open and note the output of following command
   ps faux | grep ssh-agent | wc -l
2. Login and logout using X2Go.
3. Run the above command again and notice that the resulting count increases by 1.

Expected:  The counts from steps 1 and 3 should be the same.

**Comment by paimpozhil** [comment]
I see this as well. I will try posting this in the x2go user list as I
think it could be related x2go  itself

On Sun, Jun 15, 2014 at 9:11 PM, Gurjeet Singh notifications@github.com
wrote:

> I am using the lxde/Dockerfile to create a container, and I noticed that
> every time I login and logout from X2Go client, a new ssh-agent process is
> left behind.
> 
> How to test:
> 
>    1.
> 
>    Keep one console open and note the output of following command
>    ps faux | grep ssh-agent | wc -l
>    2.
> 
>    Login and logout using X2Go.
>    3.
> 
>    Run the above command again and notice that the resulting count
>    increases by 1.
> 
> Expected: The counts from steps 1 and 3 should be the same.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/paimpozhil/DockerX2go/issues/3.

## 

Paim Pozhil

**Comment by paimpozhil** [comment]
This issue is specific to Lxde

This didnt happen in Centos/XFCE

https://bugs.launchpad.net/ubuntu/+source/gnome-session/+bug/1244736

I believe this is not particularly related to Docker.
